<aside>
               <div class="static-widget-container">
                  <div id="createPostWidget" class="w-100 mb3 ba b--black-20 pa3 gtm-widget"><span class="f4 db mb3">Having any Doubts or Queries?</span><button type="button" id="open-create-post-widget-button" class="bn bg-green white pa3 w-100 outline-0 pointer">ASK NOW</button></div>
                  <div class="w-100 gtm-widget mb3 gtm-widget" data-creative="Ace_IBPS_Clerk_SFT" id="Ace_IBPS Clerk_SFT" data-sticky="false"><a class="w-100 db" target="_blank" href="https://courses.gradeup.co/batch/a2a863f2-d8a9-11e9-a21b-0a99e0cf8f3a?utm_medium=Ace_IBPS_Clerk&amp;utm_campaign=widget"><img alt="Ace_IBPS Clerk_SFT" class="db w-100" src="<?php echo asset('assets/user/image/widget-img1568876307658-57.png')?>"></a></div>
                  <div class="w-100 gtm-widget mb3 gtm-widget" data-creative="Bank_IBPS_Plus" id="Bank_IBPS_Plus_teaser" data-sticky="true"><a class="w-100 db" target="_blank" href="https://gradeup.co/online-test-series/banking-insurance/ibps-2019-plus-pack-zjxk6evwn"><img alt="Bank_IBPS_Plus_teaser" class="db w-100" src="<?php echo asset('assets/user/image/side_widget_ts3-2-img1564203306400-98.png')?>"></a></div>
                  <div class="w-100 gtm-widget mb3 gtm-widget" data-creative="RRBNTPC_Home_Widget1" id="RRBNTPC_Home_Widget1" data-sticky="false"><a class="w-100 db" target="_blank" href="https://gradeup.co/online-test-series/ssc-railways/rrb-ntpc-2019-test-series-zjsbhi4x3"><img alt="RRBNTPC_Home_Widget1" class="db w-100" src="<?php echo asset('assets/user/image/wb1-img1551073880816-49.webp')?>"></a></div>
               </div>
               <div class="sticky-widget-container sticky-container" style="position: sticky; top: 80px;">
                  <div class="w-100 gtm-widget mb3 gtm-widget" data-creative="Ensure_LIC_SFT" id="Ensure_LIC_SFT" data-sticky="true"><a class="w-100 db" target="_blank" href="https://courses.gradeup.co/batch/0c00130c-db04-11e9-a21b-0a99e0cf8f3a?utm_campaign=widget&amp;utm_medium=ensure_lic&amp;utm_source=gradeup"><img alt="Ensure_LIC_SFT" class="db w-100" src="<?php echo asset('assets/user/image/ensure_lic_side_widget-img1569418297034-11.png')?>"></a></div>
               </div>
            </aside>